<a href="https://colab.research.google.com/github/sepehrcodereshraghisamani/numpy_exercises/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy workshop for more exercising

In [ ]:
import numpy

let's compare list vs NumpyArrays

In [ ]:
from time import process_time

typical_list = [i for i in range(100000)]
begin_time = process_time()
typical_list = [i+3 for i in typical_list]
end_time = process_time()
print(end_time - begin_time)

0.014616391999999756


In [ ]:
Numpy_array = numpy.array([i for i in range(100000)])
begin_time = process_time()
Numpy_array += 3
end_time = process_time()
print(end_time - begin_time)

0.0007714019999998101


Creating Numpy arrays with initialized values

In [ ]:
y = numpy.ones((7,8))
print(y)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
x = numpy.zeros((6,7))
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#identity matrix
a = numpy.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# a numpy array with specific vlues
z = numpy.full((5,4), 7)
print(z)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
# an array with random digits
x1 = numpy.random.random((5,4))
print(x1)

[[0.79678897 0.42764948 0.60641099 0.37542098]
 [0.36842346 0.09228554 0.66674724 0.73834701]
 [0.21120304 0.49960952 0.34181531 0.99635041]
 [0.41858705 0.01458324 0.17971791 0.54145729]
 [0.90529138 0.16107254 0.84390445 0.33934554]]


In [ ]:
# array with random integers
x2 = numpy.random.randint(100,200, size=(5,4))
print(x2)

[[192 190 112 161]
 [172 156 188 157]
 [195 170 153 140]
 [112 142 198 134]
 [148 108 128 184]]


In [ ]:
# an array that contains a range of evenly spaced intervals
x3 = numpy.arange(20,40,3)
print(x3)


[20 23 26 29 32 35 38]


In [ ]:
# # an array with values that are spaced linearly in a specified interval with saying number of values needed
x4 = numpy.linspace(10,34,num = 9)
print(x4)

[10. 13. 16. 19. 22. 25. 28. 31. 34.]


In [ ]:
# how to convert a typical list to a numpy array
list2 = [1,2,3,4,5,6,7,8,9]
numpy_array = numpy.asarray(list2)
print(numpy_array)
type(numpy_array)

[1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [ ]:
# scan different aspects of a numpy array
a1 = numpy.random.randint(1,100, size=(6,9))
print(a1)

[[62 77 16 92 81 99  8 56 90]
 [77 15 96 47 56 34 17 92 43]
 [ 9 13 70 41 74 64 49 11 21]
 [67 51 72 96 97 64 87 92 59]
 [89 32 83 96 62 13 88 49 51]
 [49 83 89  4 83 69 48 61 46]]


In [ ]:
# dimension of array
print(a1.ndim)

2


In [ ]:
# number of elements stored along each dimension of the array
print(a1.shape)

(6, 9)


In [ ]:
# number of elements in an array
print(a1.size)

54


In [ ]:
# data type of values in array
print(a1.dtype)

int64


In [ ]:
# different mathematical operations on numpy arrays
x1 = numpy.random.randint(10,30,size=(2,3))
x2 = numpy.random.randint(30,90,size=(2,3))
print(x1)
print(x2)

[[16 23 12]
 [27 20 16]]
[[62 48 36]
 [74 33 46]]


In [ ]:
print(numpy.add(x1,x2))
print(numpy.subtract(x1,x2))
print(numpy.multiply(x1,x2))
print(numpy.divide(x1,x2))


[[ 78  71  48]
 [101  53  62]]
[[-46 -25 -24]
 [-47 -13 -30]]
[[ 992 1104  432]
 [1998  660  736]]
[[0.25806452 0.47916667 0.33333333]
 [0.36486486 0.60606061 0.34782609]]


In [ ]:
# or simply use operators
print(x1 + x2)
print(x1 - x2)
print(x1 * x2)
print(x1 / x2)

[[ 78  71  48]
 [101  53  62]]
[[-46 -25 -24]
 [-47 -13 -30]]
[[ 992 1104  432]
 [1998  660  736]]
[[0.25806452 0.47916667 0.33333333]
 [0.36486486 0.60606061 0.34782609]]


#some other useful functions

In [ ]:
array1 = numpy.random.randint(1,100, size=(2,3))
print(array1)
print(array1.shape)

[[36 75 42]
 [98 43 10]]
(2, 3)


In [ ]:
# transpose or T
array2 = array1.T
print(array2)
print(array2.shape)

[[36 98]
 [75 43]
 [42 10]]
(3, 2)


In [ ]:
array3 = numpy.transpose(array1)
print(array3)
print(array3.shape)

[[36 98]
 [75 43]
 [42 10]]
(3, 2)


In [ ]:
# reshape
n1 = numpy.random.randint(1,100, size=(2,3))
print(n1)
print(n1.shape)

[[25 40 36]
 [34 84  4]]
(2, 3)


In [ ]:
n2 = n1.reshape(3,2)
print(n2)
print(n2.shape)

[[25 40]
 [36 34]
 [84  4]]
(3, 2)
